# Usando imagem do Node.js
FROM node:18-alpine

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando os arquivos do Worker
COPY ./workers/sender/package.json ./workers/sender/package-lock.json ./
RUN npm install --legacy-peer-deps

# Copiar os arquivos do projeto
COPY ./workers/sender ./

# Expondo a porta do Worker
EXPOSE 3002

# Iniciando o Worker
CMD ["npm", "run", "dev"]