

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: campaign
      POSTGRES_PASSWORD: campaign
      POSTGRES_DB: campaign
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.next
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - frontend
      - backend

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
    deploy:
      replicas: 3
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - nestjs
    networks:
      - frontend

networks:
  frontend:
  backend: